# Generated by Django 4.2.5 on 2023-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
